### ISSUE TITLE
メニュー表示等の日本語が豆腐（文字化け）

### ISSUE THREAD

**Issue by murasesyuka** [saidenka/Blender-Scramble-Addon#2]
README手順で、日本語化してない英語UIでインストールすると、文字化け。
English-speaking peopleだけでなく、日本人も「International Fonts」をONは、手順として必須では？

日本語話者が、みんな日本語化UIつかってるわけではないし

* windows7 / 8.1
* blender2.74_64bit

**Comment by saidenka** [comment]
その通りですね、README.mdを修正しました。
ご意見ありがとうございます。

**Comment by murasesyuka** [comment]
対応ありがとうございます。
