### ISSUE TITLE
pose library move up down

### ISSUE THREAD

**Issue by meta-androcto** [saidenka/Blender-Scramble-Addon#3]
hello,
your addon is looking great, I have been working on modify 
* some translate & add new features & Icons.

I see the feature to move Up/Down in DATA_PT_vertex_colors.py & DATA_PT_uv_texture.py
class MoveActiveUV(bpy.types.Operator):
	bl_idname = "object.move_active_uv"

Would this be possible for Pose Library? This would be a great feature. Top artist "Draguu"  & others have requested this feature. I would be most helpful.
Could you please make
class MoveActivePOSE(bpy.types.Operator):
	bl_idname = "object.move_active_pose"

your development is very fast & good, your ideas for the Blender Interface are very well done.
I hope you can help with my request.

Thank You.
Brendon.

**Comment by saidenka** [comment]
Done!
https://github.com/saidenka/Blender-Scramble-Addon/commit/8d389695b1e1743b6d2e8eb41ee8253a895345fb
![new](http://i.imgur.com/34Pe3Hv.png)

**Comment by meta-androcto** [comment]
Thank you very much for your quick action.
:)
